"""Voltage-aware clearance rules for the discharger PCBs.

CLAUDE.md: ≥ 6 mm between copper at different high potentials, based on ≥ 1 mm per 100 V
(600 V, uncoated). Instead of 6 mm between every pair of HV nets, each net pair gets
1 mm per 100 V of the worst-case voltage difference it can actually see, so HV ↔ GND/LV
stays at 6 mm while neighbouring divider nodes (≤150 V apart) need ~1.5 mm.

Worst case is taken over these states of a 600 V capacitor (k = node's fraction of HVp):
  fwd / rev   normal discharge, probe A or probe B positive, Q2 off
  blown_*     F1 open: bridge still at 600 V, everything after F1 at 0 V
  tf_open     TF1 open: R_fast side at HVp, Q2 drain floating at ~0 V
  q2_on       fast path conducting: HVp ≤ 85 V (worst threshold corner 83 V)
"""

V = 600.0
VQ = 85.0
MIN_CLEAR = 0.4   # mm, also the default net-class clearance

# fraction of HVp for the resistor-chain nodes (named after the resistor whose pad 2 they are)
K = {"/HVp": 1.0}
for i, k in enumerate((0.8, 0.6, 0.4, 0.2), 1):
    K[f"Net-(R_slow{i}-Pad2)"] = k
    K[f"Net-(R_sig{i}-Pad2)"] = k
for i, k in enumerate((0.75, 0.5, 0.25), 1):
    K[f"Net-(R_LED{i}-Pad2)"] = k

SCENARIOS = ("fwd", "rev", "blown_fwd", "blown_rev", "tf_open", "q2_on")
HV_NETS = ["/PROBE_A", "/PROBE_B", "/BRIDGE_P", "Net-(R_fast1-Pad2)", "Net-(Q2-D)"] + list(K)


def volt(net, s):
    if net == "/PROBE_A":
        return {"fwd": V, "blown_fwd": V, "tf_open": V, "q2_on": VQ}.get(s, 0.0)
    if net == "/PROBE_B":
        return {"rev": V, "blown_rev": V}.get(s, 0.0)
    if net == "/BRIDGE_P":
        return VQ if s == "q2_on" else V
    hvp = {"blown_fwd": 0.0, "blown_rev": 0.0, "q2_on": VQ}.get(s, V)
    if net in K:
        return K[net] * hvp
    if net == "Net-(R_fast1-Pad2)":   # R_fast–TF1 node: HVp unless Q2 conducts
        return 2.0 if s == "q2_on" else hvp
    if net == "Net-(Q2-D)":           # drain: HVp while Q2 is off and TF1 intact
        return hvp if s in ("fwd", "rev") else 2.0 if s == "q2_on" else 0.0
    return 0.0                        # LV nets (≤ 12 V) and GND


def delta_v(a, b):
    return max(abs(volt(a, s) - volt(b, s)) for s in SCENARIOS)


def clearance(a, b):
    """mm, rounded up to 0.1 mm."""
    c = max(MIN_CLEAR, delta_v(a, b) / 100.0)
    return round(-(-c * 10 // 1) / 10, 1)


def dru(all_nets, extra=""):
    """Custom-rules file text: one rule per HV net pair and per HV net vs. all LV copper."""
    hv = [n for n in HV_NETS if n in all_nets]
    lv = [n for n in all_nets if n not in hv and n]
    out = ["(version 1)", "",
           "# Generated by hv_rules.py: clearance = 1 mm per 100 V of worst-case voltage difference.", ""]
    for i, a in enumerate(hv):
        for b in hv[i + 1:]:
            c = clearance(a, b)
            if c > MIN_CLEAR:
                out.append(f'(rule "{a} | {b}"\n    (condition "(A.NetName == \'{a}\' && B.NetName == \'{b}\') || '
                           f'(A.NetName == \'{b}\' && B.NetName == \'{a}\')")\n    (constraint clearance (min {c}mm)))')
        # LV side: everything not in the HV list (GND and ≤12 V nets) sits at ~0 V
        c = clearance(a, "/GND")
        cond = " || ".join(f"B.NetName == '{n}'" for n in lv)
        out.append(f'(rule "{a} | LV"\n    (condition "A.NetName == \'{a}\' && ({cond})")\n'
                   f'    (constraint clearance (min {c}mm)))')
        out.append(f'(rule "LV | {a}"\n    (condition "B.NetName == \'{a}\' && ({cond.replace("B.", "A.")})")\n'
                   f'    (constraint clearance (min {c}mm)))')
    return "\n".join(out) + "\n" + extra


if __name__ == "__main__":
    for a in HV_NETS:
        print(f"{a:24s}", " ".join(f"{clearance(a, b):4.1f}" for b in HV_NETS + ["/GND"]))
